### ISSUE TITLE
AttributeError: module 'louvain' has no attribute 'set_rng_seed'

### ISSUE THREAD

**Issue by 1cm-cyber** [pachterlab/GSP_2019#2]
Hello， I am trying to analysis the CITE-seq data using protaccel totally following the 'CITE-seq protein acceleration analysis' in the github.

I got the following error when I ran "[cluster_ID, num_clusters] = pa.identify_clusters(vlm,vlm.connectivity,correct_tags=True,tag_correction_list=t_cl,method_name='ModularityVertexPartition')":
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.conda/envs/protaccel/lib/python3.9/site-packages/protaccel/protaccel.py", line 175, in identify_clusters
    partition_kwargs["seed"] = random_state
AttributeError: module 'louvain' has no attribute 'set_rng_seed'

Python 3.9.12

Versions:
bezier 2021.2.12，louvain 0.7.1， matplotlib 3.5.1，numpy 1.21.5， pandas 1.4.3， protaccel 0.301，pysam 0.19.1，velocyto 0.17.17

**Comment by gennadygorin** [comment]
I apologize for the late response, and thank you for bringing this to my attention. For some context, `protaccel` is not one of the current strategic priorities. At this time, I am working on wrapping up my dissertation. In addition, as outlined in a [later article](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010492), I see limited long-term prospects for velocity-inspired and more generally graph-based analysis methods in this field. 

Nevertheless, I do hope to go back through and fix this issue for the sake of reproducibility in the coming months. This is a tough problem. Louvain needs to be at 0.6.1. For reasons which are obscure to me, `pip install`ing this version or its `igraph` prerequisites fails at the wheel level. I will need to try other versions, or possibly remove the seeding call altogether. If you succeed in solving this issue, please submit a pull request.
